[server]
headless = true

[theme]
primaryColor="#4CAF50"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#E0E0E0"
textColor="#000000"
font="sans serif"

[browser]
gatherUsageStats = false

[ui]
hideMenu=true
hideFooter=true
