[server]
headless = true

[theme]
primaryColor="#4CAF50"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#E0E0E0"
textColor="#000000"
font="sans serif"

div.stFileUploader>div>div>div>label {
    font-size: 20px;   /* tamanho do texto */
}

[browser]
gatherUsageStats = false

[ui]
hideMenu=true
hideFooter=true
